### PR TITLE
fixes typo and related test

### PR DESCRIPTION
**Pull request by paco-walkme**
What does this PR do?
We have a typo of a missing / when calculating the URL of WalkMe.

Are there breaking changes in this PR?
no

Testing
Added extra test to specifically check that we are loading production proprely.
Fixed test giving false positives

Testing completed successfully in local via unit tests

Any background context you want to provide?
n/a

Is there parity with the server-side/android/iOS integration components (if applicable)?
n/a

Does this require a new integration setting? If so, please explain how the new setting works
n/a

Links to helpful docs and other external resources
n/a

### CODE REVIEW

**Comment by varadarajan-tw** [comment]
Hey @paco-walkme, I initiated a revert of the previous PR change. We'll try to get this fix in this week.

**Review by pooyaj — APPROVED** [review]

**Comment by paco-walkme** [comment]
Hi Varadarajan,

We appreciate it a lot.
Thanks you and sorry for inconvenience caused.

Paco

**Comment by varadarajan-tw** [comment]
Np @paco-walkme ! I'll initiate the rollout again tomorrow.

**Comment by varadarajan-tw** [comment]
Hey @paco-walkme, the deployment is complete!

**Comment by paco-walkme** [comment]
Thank you so much for the support! Hopefully we don’t have any more trouble
to give.

Cheers

**Pull request merged**
