### PR TITLE
Add content_type to FB Pixel InitiateCheckout

### PR DESCRIPTION
**Pull request by dja**
**What does this PR do?**
It adds the recommended standard content_type of `product` for `InitiateCheckout`, per FB documentation: https://developers.facebook.com/docs/facebook-pixel/reference/

**Are there breaking changes in this PR?**
No.

**Has this been tested end-to-end? Please provide screenshots on how the fix now populates in the end tool. If not, what was done to test?**

**Any background context you want to provide?**

**Is there parity with the server-side/android/iOS integration (if applicable)?**

**Does this require a metadata change? If so, please link the PR from https://github.com/segmentio/destination-scripts.**

**What are the relevant tickets?**

**Link to CC ticket**

**List all the tests accounts you have used to make sure this change works**

**Helpful Docs**

### CODE REVIEW

**Comment by CarlosMecha** [comment]
Hi @dja Could you post where the documentation recommends use `content_type` for `InitiateCheckout`?

These are the fields listed for that event in the link you posted:
 * `content_category`
 * `content_ids` 
 * `contents`
 * `currency`
 * `num_items`
 * `value`

**Comment by dja** [comment]
Hi @CarlosMecha, this is a warning we see through the Facebook Pixel Helper (screenshot: https://d.pr/i/xViBj8), and is loosely documented here: https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-audiences#setuppixel

It seems that if `content_ids` is present, Facebook wants `content_type` alongside it.

**Comment by CarlosMecha** [comment]
@dja yeah, I was able to reproduce. I'll keep you updated. Thanks!

**Comment by CarlosMecha** [comment]
Hi @dja . We are currently starting the release process for this change, I'll leave this PR open until the release is fully done (beginning of next week if no issues). See #143

**Comment by CarlosMecha** [comment]
Hi @dja, this change has been fully released :)

**Pull request closed without merging**
