### PR TITLE
Track every VWO experiment only once

### PR DESCRIPTION
**Pull request by gauravmuk**
**What does this PR do?**
Fixes https://github.com/segmentio/analytics.js-integrations/issues/494

**Are there breaking changes in this PR?**
No

**Testing**
Testing completed successfully.
All changes in this PR were made locally in the analytics.js file, and the file was mapped using a web proxy.
Loom Video highlighting the fix https://www.loom.com/share/764879f33ef0423b92d637df06942141

**Any background context you want to provide?**

**Is there parity with the server-side/android/iOS integration components (if applicable)?**

**Does this require a new integration setting? If so, please explain how the new setting works**

**Links to helpful docs and other external resources**

### CODE REVIEW

**Comment by gauravmuk** [comment]
@juliofarah @gaurishanker @danieljackins Can you please review this PR?

**Comment by gauravmuk** [comment]
@juliofarah @danieljackins @pooyaj Can you please review this PR?

**Review by pooyaj — COMMENTED** [review]
@gauravmuk Could you please update the History.md with the description of the change?

**Comment by gauravmuk** [comment]
> @gauravmuk Could you please update the History.md with the description of the change?

Updated HISTORY.md with the changes.

**Comment by gauravmuk** [comment]
@pooyaj Can you please review this and let me know if any more updates are required?

**Review by pooyaj — APPROVED** [review]

**Comment by gauravmuk** [comment]
@pooyaj @juliofarah i see the buildkite status is somehow not reflecting in the merge checks. i hope that will not be a blocker for us to get this merged.

**Comment by pooyaj** [comment]
@gauravmuk Yes, looking into that. Also looks like 2.4.3 is already published without being reflected in the Changelog. Could you please: 
* Let's bump the entry on HISTORY.md to 2.4.4
* Update the `package.json` version to 2.4.4 as well so the new version get's published to npm

**Comment by gauravmuk** [comment]
> @gauravmuk Yes, looking into that. Also looks like 2.4.3 is already published without being reflected in the Changelog. Could you please:
> 
> * Let's bump the entry on HISTORY.md to 2.4.4
> * Update the `package.json` version to 2.4.4 as well so the new version get's published to npm

Done. It's 2.4.4 in HISTORY.md and package.json

**Comment by pooyaj** [comment]
Perfect 💥

**Comment by gauravmuk** [comment]
@pooyaj One last question perhaps, how long will it take for this change to reflect as part of Segment's analytics.js?

**Comment by pooyaj** [comment]
@gauravmuk will start a gradual rollout today. Probably everyone will get this by the mid next week.

**Comment by gauravmuk** [comment]
Thanks again @pooyaj

**Pull request merged**
