### PR TITLE
[Hindsight / Rockerbox] Add Custom Domain Option

### PR DESCRIPTION
**Pull request by mericsson**
Merging https://github.com/segmentio/analytics.js-integrations/pull/511 on behalf of @skarim

https://segment.atlassian.net/browse/STRATCONN-509
https://segment.atlassian.net/browse/CC-7107

---

**What does this PR do?**
Adds additional options for users to enter a custom domain & disable cross-domain syncing for their Rockerbox tracker.

**Are there breaking changes in this PR?**
No

**Any background context you want to provide?**
With more browsers blocking third-party cookies, Rockerbox is enabling customers to create a subdomain under their own domain (first-party) that CNAMEs Rockerbox's servers. Rockerbox's Segment integration as currently configured is hardcoded to use a Rockerbox domain and doesn't allow the user to customize this.

Also, please note that "Hindsight" is a legacy product name and the actual integration is now listed as "Rockerbox" in the Segment UI.

**Is there parity with the server-side/android/iOS integration components (if applicable)?**
N/A

**Does this require a new integration setting? If so, please explain how the new setting works**
Yes. The new integration settings would be a text input field named "Custom Tracking Domain" and a switch labeled "Enable Rockerbox Cookie Sync" in the Segment UI.

**Links to helpful docs and other external resources**
Our support doc for Segment is available at https://help.rockerbox.com/docs/segment-pixel-implementation

### CODE REVIEW

**Comment by mericsson** [comment]
@briemcnally Looks like circleci_enterprise is broken. But I think buildkite is what we are using these days? Can we just remove circleci_enterprise?

**Comment by briemcnally** [comment]
Yeah originally  Carlos wanted us to keep Circle CI so that some kind of CI could be ran for PRs submitted by contractors and external contributors. It was basically so internal reviewers could spot failing tests and changes  to dependencies early. I'm not sure how frequently we are reviewing contractor/3rd party PR reviews for a.js, but it seems like we are OK to remove now. Will leave up to you.

**Comment by mericsson** [comment]
> Yeah originally Carlos wanted us to keep Circle CI so that some kind of CI could be ran for PRs submitted by contractors and external contributors. It was basically so internal reviewers could spot failing tests and changes to dependencies early. I'm not sure how frequently we are reviewing contractor/3rd party PR reviews for a.js, but it seems like we are OK to remove now. Will leave up to you.

sgtm - I removed the webhook for now.

**Review by briemcnally — APPROVED** [review]
LGTM 🚢

**Comment by briemcnally** [comment]
@mericsson let's just make sure we add the new settings to PP before rolling out on release train: https://app.segment.com/partner-portal/integration/drift/settings

**Comment by briemcnally** [comment]
@mericsson let's make sure we add the settings to PP before rollout on release train: https://app.segment.com/partner-portal/integration/hindsight/settings

**Comment by mericsson** [comment]
Added new settings. Will unhide after fully released.

image

image

**Comment by mericsson** [comment]
@skarim were you able to test this end to end at all? Do you have a test segment account? I can enable it for a workspace / source.

**Comment by skarim** [comment]
@mericsson yup I was able to test the updates locally by [following the instructions to compile analytics.js](https://github.com/segmentio/analytics.js-integrations/tree/master/compiler) and running some tests with our test workspace. I checked the different settings by [compiling with custom settings](https://github.com/segmentio/analytics.js-integrations/tree/master/compiler), but it would be good to do a full end-to-end using the UI. Can you enable this on the `rockerbox-sandbox` workspace?

**Comment by mericsson** [comment]
> @mericsson yup I was able to test the updates locally by [following the instructions to compile analytics.js](https://github.com/segmentio/analytics.js-integrations/tree/master/compiler?rgh-link-date=2020-12-17T09%3A39%3A30Z) and running some tests with our test workspace. I checked the different settings by [compiling with custom settings](https://github.com/segmentio/analytics.js-integrations/tree/master/compiler?rgh-link-date=2020-12-17T09%3A39%3A30Z), but it would be good to do a full end-to-end using the UI. Can you enable this on the `rockerbox-sandbox` workspace?

Thanks will do and update here once it is enabled for you.

**Comment by mericsson** [comment]
@skarim it should now be enabled for that all existing sources in that workspaces (new sources in that workspace won't get it) -- give it a try when you have a chance and let me if it looks good.

**Comment by skarim** [comment]
@mericsson I tested the updated destination and combinations of the different settings and everything looks good to me. Ran this through our selenium tests too and verified the output matches what we're expecting ✅ 

Thanks for all your help getting this merged! How will this be rolled out to production for Segment customers?

**Comment by mericsson** [comment]
@skarim Great! I expect this will be released in a staged rollout to all customers starting Jan 4, completing Jan 6 or 7. Will update here when complete.

**Comment by mericsson** [comment]
@skarim Sorry slight delay. Release will complete Monday Jan 11. It is available to free & self service customers at the moment.

**Comment by mericsson** [comment]
@skarim this is now fully deployed

**Pull request merged**
