### PR TITLE
camelcased custom props in fullstory

### PR DESCRIPTION
**Pull request by stevenmiller888**
@f2prateek @amillet89 Let me know how it looks!

### CODE REVIEW

**Comment by stevenmiller888** [comment]
@f2prateek @amillet89  - Can you take a look?

**Comment by stevenmiller888** [comment]
@f2prateek @amillet89 Bueller? bueller? Haha :)

**Comment by f2prateek** [comment]
Do you know where the CI errors are from?

**Comment by stevenmiller888** [comment]
Nope, I'm not getting those errors locally. But based on the error messages...

`Error loading resource http://api.segment.io/v1/p (5). Details: Operation canceled`

... looks totally unrelated to me. What do you think?

**Comment by f2prateek** [comment]
yeah I'm not too sure what's going on with Circle, LGTM otherwise though.

**Comment by f2prateek** [comment]
I'll run this locally today and merge in if the tests are passing.

**Comment by ndhoule** [comment]
Don't merge unless Circle is passing—generally that points to an environmental problem that should be fixed.

**Comment by f2prateek** [comment]
Fixed!

**Pull request merged**
