### PR TITLE
Fix UUID

### PR DESCRIPTION
**Pull request by gaurishanker**
**What does this PR do?**
This pull request adds the VWO UUID as a trait in track and identify call. 

**Are there breaking changes in this PR?**
No

**Testing**

Testing completed successfully via end-to-end tests with the related change of adding UUID in the VWO object and identify call.
Attaching a loom video showing UUID is passed on each page load in track and identify calls. For the purpose of making this video, all changes in this PR were made locally in the analytics.js file, and the file was mapped using a web proxy.
https://www.loom.com/share/40f8522af0ab4723af6dd3ca4df85c7f

**Any background context you want to provide?**

**Is there parity with the server-side/android/iOS integration components (if applicable)?**

**Does this require a new integration setting? If so, please explain how the new setting works**

**Links to helpful docs and other external resources**

### CODE REVIEW

**Comment by gaurishanker** [comment]
@mericsson @gurdasnijor Can you please help us in identifying people who will be able to review this PR?

**Comment by mericsson** [comment]
Thanks for your contribution. @gaurishanker can you email partners@segment.com to prioritize this request? Please include any relevant information about customers requesting this update. Thank you!

**Comment by mericsson** [comment]
Correction: use partner-support@segment.com

**Comment by gaurishanker** [comment]
Thanks, @mericsson for the update. I have sent an email to  partner-support@segment.com regarding the same.

**Comment by juliofarah** [comment]
Hey folks!
I'm sorry we took so long to reply on our side.

I have just picked this up, the code looks good to me and this looks like simple changes.
Although, I'm not able to test them on my side.

I have setup a VWO account and was able to get the snippet injected by using the smart sync option, but it looks like the data needed to generate the uuid is not available. Here are some screenshots that might help debug.

image
image

I would appreciate some help testing these changes end to end so I could go ahead and merge this PR.

In addition, could you update the PR description with a couple of screenshots showing the that the data is shown on the track and identify calls?

Thanks in advance

**Comment by juliofarah** [comment]
> Hey folks!
> I'm sorry we took so long to reply on our side.
> 
> I have just picked this up, the code looks good to me and this looks like simple changes.
> Although, I'm not able to test them on my side.
> 
> I have setup a VWO account and was able to get the snippet injected by using the smart sync option, but it looks like the data needed to generate the uuid is not available. Here are some screenshots that might help debug.
> 
> image
> image
> 
> I would appreciate some help testing these changes end to end so I could go ahead and merge this PR.
> 
> In addition, could you update the PR description with a couple of screenshots showing the that the data is shown on the track and identify calls?
> 
> Thanks in advance

cc @gaurishanker

**Comment by gaurishanker** [comment]
Hi @juliofarah 

Sorry for the late reply. We investigated the issue because of which you were not able to get UUID on the page.
We saw that you ran an experiment on localhost which is not recommended. You can try running a test using https://gaurishanker.github.io/testing.html?id=555678, here "id" param takes VWO account id.
NOTE: You have to run an AB test using above mentioned URL.

If you want to use your own website/URL please make sure that it is not localhost.

**Comment by juliofarah** [comment]
Thanks for the reply @gaurishanker 
Could you folks update the PR description with evidence that the changes work? Ideally, we'd like to see the identify call being made on page load and the uuid being sent on both identify and track calls

Thanks again

**Comment by gaurishanker** [comment]
@juliofarah We have attached a video in the description of PR showing identify being called on page load and UUID being passed in both identify and track calls.

**Review by juliofarah — APPROVED** [review]

**Comment by juliofarah** [comment]
Thanks @gaurishanker 
I will update this branch and kick off the release process.

**Pull request merged**
