### PR TITLE
Update rollbar destination to 2.21.1

### PR DESCRIPTION
**Pull request by waltjones**
**What does this PR do?**

Bumps rollbar.js version: 2.13.0 -> 2.21.1

**Are there breaking changes in this PR?**

No

**Testing**

Testing completed successfully on local 

**Any background context you want to provide?**

**Is there parity with the server-side/android/iOS integration components (if applicable)?**

N/A

**Does this require a new integration setting? If so, please explain how the new setting works**

No

**Links to helpful docs and other external resources**

https://github.com/rollbar/rollbar.js/releases

### CODE REVIEW

**Comment by waltjones** [comment]
@danieljackins Asking since it looks like you are active in this project. Can you let me know if there are any additional steps I should take for this to be merged?

**Comment by pooyaj** [comment]
hey @waltjones, thanks for the PR! Few requests: 
- are there any breaking changes in the upgrade? 
- Also can you please point me to the source (rollerbar CDN or docs or somewhere else) where the updated minified JS is coming from?

**Comment by waltjones** [comment]
Hi @pooyaj thanks for the follow up. No breaking changes. The CDN location pointed to by this PR is here: https://cdn.rollbar.com/rollbarjs/refs/tags/v2.21.1/rollbar.min.js

**Comment by pooyaj** [comment]
@waltjones looks like the content of the https://cdn.rollbar.com/rollbarjs/refs/tags/v2.21.1/rollbar.min.js is different from the updated blob. Since the changed blob is minified, I am looking for a way to verify the integrity of the content. What would be the best way to do that?

**Comment by pooyaj** [comment]
Update: checked the script integrity via Rollerbar dashboard. This looks good to go

**Review by pooyaj — APPROVED** [review]

**Comment by waltjones** [comment]
@pooyaj Thank you!

**Pull request merged**
