### PR TITLE
vwo/migrate destination codebase

### PR DESCRIPTION
**Pull request by ccnixon**
**What does this PR do?**
Imports the VWO integration code into this repo.

### CODE REVIEW

**Comment by CarlosMecha** [comment]
Hey @ccnixon where is this code hosted? I can't find it in the segment-integrations organization

**Comment by ccnixon** [comment]
@CarlosMecha - https://github.com/segment-integrations/analytics.js-integration-visual-website-optimizer

**Comment by CarlosMecha** [comment]
Hey @ccnixon , I've opened #190. I would recommend to use the tool we have for migrating integrations to the monorepo. It also updates the other repo with some information about where the code has been moved (including issues/PRs).

**Comment by ccnixon** [comment]
Closing in favor of: https://github.com/segmentio/analytics.js-integrations/pull/190

**Pull request closed without merging**
